import type { Metadata } from "next";
import { Raleway} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";



const raleway = Raleway({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Saibhreas Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={raleway.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
        </ThemeProvider>    
      </body>
    </html>
  );
}
